apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-volume
  labels:
    type: local
spec:
  volumeMode: Filesystem
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/host/temp/nginx"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: nginx-volume
